# AUTOGENERATED! DO NOT EDIT! File to edit: src/tree_edge.ipynb (unless otherwise specified).

__all__ = ['TreeEdge']

# Cell
from .value import Value
from .tree_node import TreeNode

# Cell
class TreeEdge:
    def __init__(self, value: Value, child: TreeNode):
        self.value = value
        self.child = child
