# AUTOGENERATED! DO NOT EDIT! File to edit: src/uncertain_entropy_evaluator.ipynb (unless otherwise specified).

__all__ = ['UncertainEntropyEvaluator']

# Cell
from .data import Data
from .entropy_evaluator import EntropyEvaluator

# Cell
class UncertainEntropyEvaluator(EntropyEvaluator):

    def calculate_entropy(self, data: Data) -> float:
        pass