image: alpine:latest

pages:
  stage: deploy
  script:
  - mkdir public
	- cp -a docs/* public/
	# or
	# - cp src/*.html public
	# - cp src/*.css public
	# - cp src/*.js public
	# - cp src/*.jpg public
  artifacts:
    paths:
    - public
  only:
  - master
