# AUTOGENERATED! DO NOT EDIT! File to edit: src/data_scrambler.ipynb (unless otherwise specified).

__all__ = ['DataScrambler', 'configuration']

# Cell
class DataScrambler:
    def __init__(self):
        pass

# Cell
class configuration:
    def __init__(self, att_name: str, to_scramble: float, mistake_epsilon:float, uniform: bool):
        self.attName = att_name
        self.toScramble = to_scramble
        self.mistakeEpsilon = mistake_epsilon
        self.uniform = uniform
