# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"UId3_trest": "UId3.ipynb"}

modules = ["UId3.py"]

doc_url = "https://aleksandratal.github.io/pyuid3/"

git_url = "https://github.com/aleksandratal/pyuid3/tree/master/"

def custom_doc_links(name): return None
