# AUTOGENERATED! DO NOT EDIT! File to edit: src/att_stats.ipynb (unless otherwise specified).

__all__ = ['AttStats']

# Cell
class AttStats:
    def __init__(self, statistics: list, avg_confidence: float):
        self.statistics = statistics
        self.avg_confidence = avg_confidence

