# AUTOGENERATED! DO NOT EDIT! File to edit: src/entropy_evaluator.ipynb (unless otherwise specified).

__all__ = ['EntropyEvaluator']

# Cell
from abc import ABCMeta, abstractmethod
from .data import Data

# Cell
class EntropyEvaluator:
    __metaclass__ = ABCMeta

    @abstractmethod
    def calculate_entropy(self, data: Data) -> float:
        raise NotImplementedError