# AUTOGENERATED! DO NOT EDIT! File to edit: UId3.ipynb (unless otherwise specified).

__all__ = ['UId3_trest']

# Cell
class UId3_trest:
     def __init__(self):
        NODE_SIZE_LIMIT = 1
        TREE_DEPTH_LIMIT = 2
        GROW_CONFIDENCE_THRESHOLD = 0
