# AUTOGENERATED! DO NOT EDIT! File to edit: src/uId3.ipynb (unless otherwise specified).

__all__ = ['UId3', 'main']

# Cell
class UId3:
     def __init__(self):
        NODE_SIZE_LIMIT = 1
        TREE_DEPTH_LIMIT = 2
        GROW_CONFIDENCE_THRESHOLD = 0



# Cell
def main():
    pass

# Cell
if __name__ == "__main__":
    main()