# AUTOGENERATED! DO NOT EDIT! File to edit: src/uncertain_entropy_evaluator.ipynb (unless otherwise specified).

__all__ = ['UncertainEntropyEvaluator']

# Cell
import math

from .data import Data
from .entropy_evaluator import EntropyEvaluator

# Cell
class UncertainEntropyEvaluator(): #sEntropyEvaluator):

    def calculate_entropy(self, data: Data) -> float:
        class_att = data.get_attributes()[-1]
        probs = data.calculate_statistics(class_att)
        entropy = sum(map(lambda v: -v.get_confidence() * math.log2(v.get_confidence())  if v.get_confidence()!=0 else 0, probs.get_statistics()))
        return entropy
