# AUTOGENERATED! DO NOT EDIT! File to edit: src/attribute.ipynb (unless otherwise specified).

__all__ = ['Attribute']

# Cell
class Attribute:
    TYPE_NOMINAL = 1
    TYPE_NUMERICAL = 2

    def __init__(self, name: str, domain: set, type_of_att=TYPE_NOMINAL):
        this.name = name
        this.domain  = domain
        this.type = type_of_att
