# AUTOGENERATED! DO NOT EDIT! File to edit: src/instance.ipynb (unless otherwise specified).

__all__ = ['Instance']

# Cell
class Instance:
    def __init__(self, readings = []):
        self.readings = readings
