# AUTOGENERATED! DO NOT EDIT! File to edit: src/tree_evaluator.ipynb (unless otherwise specified).

__all__ = ['TreeEvaluator', 'BenchmarkResult', 'Prediction', 'Stats']

# Cell
from .att_stats import AttStats

# Cell
class TreeEvaluator:
    def __init__(self):
        pass

# Cell
class BenchmarkResult:
    def __init__(self):
        pass

# Cell
class Prediction:
    def __init__(self, prediction: AttStats, correct_label: str):
        self.prediction = prediction
        self.correctLabel = correctLabel

# Cell
class Stats:
    def __init__(self, class_label):
        self.class_label = class_label