# AUTOGENERATED! DO NOT EDIT! File to edit: src/value.ipynb (unless otherwise specified).

__all__ = ['Value']

# Cell
class Value:
    def __init__(self, name: str, confidence: float):
        self.name = name
        self.confidence = confidence
